development:
  username: <%= `whoami`.chomp %>
  adapter: postgis
  database: inponto_dev
  pool: 5
  timeout: 5000

test:
  username: <%= `whoami`.chomp %>
  adapter: postgis
  database: inponto_test
  pool: 5
  timeout: 5000

production:
  username: <%= `whoami`.chomp %>
  adapter: postgis
  database: inponto
  pool: 5
  timeout: 5000
  