development:
  username: <%= `whoami`.chomp %>
  adapter: postgis
  database: inponto_dev
  pool: 5
  timeout: 5000
  schema_search_path: "public,postgis"

production:
  username: <%= `whoami`.chomp %>
  adapter: postgis
  database: inponto
  pool: 5
  timeout: 5000
  schema_search_path: "public,postgis"
